spring:
    data:
      mongodb:
         uri : mongodb://xxx:xxx@xxx:xxx/xxx

    datasource:
          url : jdbc:mysql://xxx:xxx/xxx
          username : xxx
          password : xxx
          driverClassName : com.mysql.jdbc.Driver
    activemq:
          broker-url: tcp://xxx:xxx
          user : xxx
          password : xxx
          pool:
              enabled: true
              max-connections: 10
custom:
    host : xxx
server:
    port : 7777

